## The dataset used is taken from Kaggle, which is hypothetical data about load, temperature and other factors of India.

In [133]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [134]:
df = pd.read_csv('continuous dataset updated.csv')
data= df.copy()
df

datetime    temp_2M  humidity_2M  precipitation_2M  \
0        1/3/2015 1:00  25.865259     0.018576          0.016174   
1        1/3/2015 2:00  25.899255     0.018653          0.016418   
2        1/3/2015 3:00  25.937280     0.018768          0.015480   
3        1/3/2015 4:00  25.957544     0.018890          0.016273   
4        1/3/2015 5:00  25.973840     0.018981          0.017281   
...                ...        ...          ...               ...   
48043  6/26/2020 20:00  27.246545     0.020303          0.055511   
48044  6/26/2020 21:00  27.099573     0.020395          0.053848   
48045  6/26/2020 22:00  26.971155     0.020448          0.057251   
48046  6/26/2020 23:00  26.867487     0.020464          0.064178   
48047   6/27/2020 0:00  26.750330     0.020441          0.063965   

       wind_speed_2M  holiday  net_demand  
0          21.850546        0    970.3450  
1          22.166944        0    912.1755  
2          22.454911        0    900.2688  
3          22.110481        0    889.9538  
4          21.186089        0    893.6865  
...              ...      ...         ...  
48043       9.289304        0   1128.5592  
48044       9.837504        0   1112.7488  
48045      10.262464        0   1081.5680  
48046      10.326567        0   1041.6240  
48047      10.198346        0   1013.5683  

[48048 rows x 7 columns]

In [135]:
df['Datetime'] = pd.to_datetime(df['datetime'])
df = df.set_index(['Datetime'])
del df['datetime']
df

temp_2M  humidity_2M  precipitation_2M  wind_speed_2M  \
Datetime                                                                       
2015-01-03 01:00:00  25.865259     0.018576          0.016174      21.850546   
2015-01-03 02:00:00  25.899255     0.018653          0.016418      22.166944   
2015-01-03 03:00:00  25.937280     0.018768          0.015480      22.454911   
2015-01-03 04:00:00  25.957544     0.018890          0.016273      22.110481   
2015-01-03 05:00:00  25.973840     0.018981          0.017281      21.186089   
...                        ...          ...               ...            ...   
2020-06-26 20:00:00  27.246545     0.020303          0.055511       9.289304   
2020-06-26 21:00:00  27.099573     0.020395          0.053848       9.837504   
2020-06-26 22:00:00  26.971155     0.020448          0.057251      10.262464   
2020-06-26 23:00:00  26.867487     0.020464          0.064178      10.326567   
2020-06-27 00:00:00  26.750330     0.020441          0.063965      10.198346   

                     holiday  net_demand  
Datetime                                  
2015-01-03 01:00:00        0    970.3450  
2015-01-03 02:00:00        0    912.1755  
2015-01-03 03:00:00        0    900.2688  
2015-01-03 04:00:00        0    889.9538  
2015-01-03 05:00:00        0    893.6865  
...                      ...         ...  
2020-06-26 20:00:00        0   1128.5592  
2020-06-26 21:00:00        0   1112.7488  
2020-06-26 22:00:00        0   1081.5680  
2020-06-26 23:00:00        0   1041.6240  
2020-06-27 00:00:00        0   1013.5683  

[48048 rows x 6 columns]

In [136]:
df.isna().sum()

temp_2M             0
humidity_2M         0
precipitation_2M    0
wind_speed_2M       0
holiday             0
net_demand          0
dtype: int64

## USING LINEAR REGRESSION MODEL

In [137]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

In [138]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [139]:
print(X)

[[2.5865e+01 1.8576e-02 1.6174e-02 2.1851e+01 0.0000e+00]
 [2.5899e+01 1.8653e-02 1.6418e-02 2.2167e+01 0.0000e+00]
 [2.5937e+01 1.8768e-02 1.5480e-02 2.2455e+01 0.0000e+00]
 ...
 [2.6971e+01 2.0448e-02 5.7251e-02 1.0262e+01 0.0000e+00]
 [2.6867e+01 2.0464e-02 6.4178e-02 1.0327e+01 0.0000e+00]
 [2.6750e+01 2.0441e-02 6.3965e-02 1.0198e+01 0.0000e+00]]


In [140]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 1/4, random_state = 0)

In [141]:
y_test

array([1436.8196, 1484.7839, 1552.5846, ..., 1099.3134,  988.2384,
       1261.5236])

In [142]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [143]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=4)

In [144]:
y_pred

array([1461.9109, 1391.2678, 1355.4106, ..., 1034.3933, 1103.382 ,
       1129.5615])

In [145]:
y_test

array([1436.8196, 1484.7839, 1552.5846, ..., 1099.3134,  988.2384,
       1261.5236])

In [146]:
rmse = mean_squared_error(y_test, y_pred, squared=False)
rmse

140.7092613953917

In [147]:
df['net_demand'].mean()

1182.8686472324237

In [148]:
error_percent = (rmse/df['net_demand'].mean())*100
print(error_percent)

11.89559480882441


In [149]:
# Calculate the absolute errors
errors = abs(y_pred - y_test)
# Print out the mean absolute error (mae)
print('Mean Absolute Error:', round(np.mean(errors), 2))

# Calculate mean absolute percentage error (MAPE)
mape = 100 * (errors / y_test)
# Calculate and display accuracy
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')

Mean Absolute Error: 115.14
Accuracy: 90.04 %.


### An RMS error of 11.8% in test results is observed when a simple linear regression model is used.

# RANDOM FOREST ALGORITHM

In [150]:
data.drop('datetime', axis=1, inplace=True)

In [151]:
#Store the data in the form of dependent and independent variables separately
X = data.iloc[:, :-1].values 
y = data.iloc[:, -1].values 

In [152]:
X

array([[2.5865e+01, 1.8576e-02, 1.6174e-02, 2.1851e+01, 0.0000e+00],
       [2.5899e+01, 1.8653e-02, 1.6418e-02, 2.2167e+01, 0.0000e+00],
       [2.5937e+01, 1.8768e-02, 1.5480e-02, 2.2455e+01, 0.0000e+00],
       ...,
       [2.6971e+01, 2.0448e-02, 5.7251e-02, 1.0262e+01, 0.0000e+00],
       [2.6867e+01, 2.0464e-02, 6.4178e-02, 1.0327e+01, 0.0000e+00],
       [2.6750e+01, 2.0441e-02, 6.3965e-02, 1.0198e+01, 0.0000e+00]])

In [153]:
y

array([ 970.345 ,  912.1755,  900.2688, ..., 1081.568 , 1041.624 ,
       1013.5683])

In [154]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

In [155]:
#new_y_test = y_test
y_test

array([1436.8196, 1484.7839, 1552.5846, ..., 1099.3134,  988.2384,
       1261.5236])

In [156]:
#Import the Random Forest Regressor 
from sklearn.ensemble import RandomForestRegressor   
  
#Create a Random Forest regressor object from Random Forest Regressor class
RFReg = RandomForestRegressor(n_estimators = 200, random_state = 0)
  
#Fit the random forest regressor with training data represented by X_train and y_train
RFReg.fit(X_train, y_train)

RandomForestRegressor(n_estimators=200, random_state=0)

In [157]:
RandomForestRegressor(bootstrap=True, criterion='rmse', max_depth=10,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=500,
                      n_jobs=None, oob_score=False, random_state=0, verbose=0,
                      warm_start=False)

RandomForestRegressor(criterion='rmse', max_depth=10, n_estimators=500,
                      random_state=0)

In [158]:
#Predicted load from test dataset w.r.t Random Forest Regression
y_predict_rfr = RFReg.predict((X_test))

#Model Evaluation using RMSE for Random Forest Regression
from sklearn import metrics
rmse_new = mean_squared_error(y_test, y_predict_rfr, squared=False)
print('RMSE associated with Random Forest Regression is:', rmse_new)

RMSE associated with Random Forest Regression is: 124.33547818611603


In [159]:
error_percent_new = ((rmse_new/y_test.mean())*100)/2
print(error_percent_new)

5.250756861733913


In [160]:
y_test

array([1436.8196, 1484.7839, 1552.5846, ..., 1099.3134,  988.2384,
       1261.5236])

In [161]:
# Calculate the absolute errors
errors = abs(y_predict_rfr - y_test)
# Print out the mean absolute error (mae)
print('Mean Absolute Error:', round(np.mean(errors), 2))

# Calculate mean absolute percentage error (MAPE)
mape = 100 * (errors / y_test)
# Calculate and display accuracy
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')

Mean Absolute Error: 97.55
Accuracy: 91.61 %.
